import pandas as pd
df=pd.read_csv("sales.csv")
print(df.head())
print(df.info())
print(df["Sales"])
print(df[["Region","Category"]])
high_sales = df[df["Sales"] > 10000]
print(high_sales)
sorted_data = df.sort_values(by="Sales", ascending=False)
print(sorted_data)
print(df.isnull().sum())
df=df.dropna()
total_sales = df["Sales"].sum()
print("Total Sales:", total_sales)
total_profit = df["Profit"].sum()
print("Total Profit:", total_profit)
category_sales = df.groupby("Category")["Sales"].sum()
print(category_sales)
region_sales = df.groupby("Region")["Sales"].sum()
print(region_sales)
top_products = df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False)
print(top_products)